# https://dev.azure.com/home-assistant

trigger:
  batch: true
  branches:
    include:
    - master
pr:
  - master

jobs:

- job: 'JQ'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: sudo apt-get install -y jq
    displayName: 'Install JQ'
  - bash: |
      shopt -s globstar
      cat **/*.json | jq '.'
    displayName: 'Run JQ to validate JSON files'
  - bash: |
        for component in components/*; do
          manifest=$(jq --raw-output ".manifest" "${component}")

          echo "Process: ${component} -> ${manifest}"
          curl -s "${manifest}" | jq -e --raw-output '.requirements[0]'
          if [[ "$?" == 1 ]]; then
            echo "Useless addition, $component does not have any requirements"
            exit 1
          fi
        done
    displayName: 'Check if integration have requirements'